services:
  sinatra:
    build: .
    platform: linux/amd64
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: concrete
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    volumes:
      - gem_volume:/usr/local/bundle
    ports:
      - 4567:4567
    tty: true
  mysql:
    image: mysql
    restart: always
    platform: linux/amd64
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: concrete
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
volumes:
  gem_volume:
  mysql_volume:
