services:
  sinatra:
    build: .
    platform: linux/amd64
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: concrete
      MYSQL_USER: concrete
      MYSQL_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - gem_volume:/usr/local/bundle
      - ./sql:/app/sql
      - ./src:/app/src
    ports:
      - 4567:4567
  mysql:
    image: mysql
    restart: always
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: concrete
      MYSQL_USER: concrete
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-ppassword", "-hlocalhost"]
      interval: 1s
      retries: 10
volumes:
  gem_volume:
  mysql_volume:
